name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Clippy, Build, Test & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            stellar-lend/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        run: |
          cd stellar-lend
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cd stellar-lend
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build project
        run: |
          cd stellar-lend
          cargo build --verbose

      - name: Run tests
        run: |
          cd stellar-lend
          cargo test --verbose

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: |
          cd stellar-lend
          cargo audit
